apiVersion: v1
data:
  odoo-account: YWRtaW4=
  odoo-password: YWRtaW4=
kind: Secret
metadata:
  name: odoo-login
  namespace: icgroup
type: Opaque
---
apiVersion: v1
data:
  pgpass: |
    cG9zdGdyZXM6NTQzMjpwb3N0Z3JlczpvZG9vLXBvc3RncmVzOnBzcWwtcGFzc3dvcmQNCn
    Bvc3RncmVzOjU0MzI6b2Rvby1kYjpvZG9vLXBvc3RncmVzOnBzcWwtcGFzc3dvcmQ=
kind: Secret
metadata:
  name: passfile
  namespace: icgroup
type: Opaque
---
apiVersion: v1
data:
  pgadmin-password: cGdhZG0tcGFzc3dvcmQ=
  postgres-password: cHNxbC1wYXNzd29yZA==
kind: Secret
metadata:
  name: passwords
  namespace: icgroup
type: Opaque
