---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pv-claim
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi