---
# Service G du plan
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8070
  selector:
    app: pgadmin
    env: prod
  type: LoadBalancer