---
# Déploiement D du plan
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
      env: prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
        env: prod
    spec:
      # Comme pour le déploiement de pgadmin, on doit donner la propriété
      # du dossier au user (linux) qui utilise l'appli
      initContainers:
      - name: change-folder-owner
        image: busybox
        command: ["sh", "-c", "chown -R 101:101 /var/lib/odoo"]
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /var/lib/odoo
      containers:
      - image: odoo:15
        name: odoo
        env:
        - name: USER
          value: odoo-postgres
        - name: HOST
          value: postgres
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: postgres-password
        - name: ODOO_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: odoo-login
              key: odoo-account
        - name: ODOO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-login
              key: odoo-password        
        ports:
        - containerPort: 8069
          name: odoo-port
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /var/lib/odoo
        # Ici, on crée une nouvelle base de données odoo-db
        # avec toutes les infos nécessaires, pour éviter d'avoir la page de configuration d'odoo :
        command:
          - "sh"
          - "-c"
          - |
            curl "192.168.56.101:8069/web/database/create" --data "master_pwd=123456&name=odoo-db&login=$(ODOO_ACCOUNT)&password=$(ODOO_PASSWORD)&phone=457858&lang=en_US&country_code=us&demo=1" --compressed
            /entrypoint.sh odoo
      volumes:
      - name: odoo-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-pv-claim
