---
# Fichier à utiliser hors du projet avec la commande 
# kubectl kustomize . > secrets.yml
# dans un dossier comprenant ce fichier, et le fichier pgpass.
# Génère un secrets.yml qui comporte toutes les infos sensibles, hashées en base64
secretGenerator:
# Mots de passe postgres et pgadmin :
- name: passwords
  namespace: icgroup
  literals:
  - postgres-password=psql-password
  - pgadmin-password=pgadm-password
# Fichier pgpass qui sera injecté dans les containers pgadmin
# pour accéder à la BDD sans interaction :
- name: passfile
  namespace: icgroup
  files:
  - pgpass
# Login et mot de passe du user d'odoo :
- name: odoo-login
  namespace: icgroup
  literals:
  - odoo-account=admin
  - odoo-password=admin
generatorOptions:
  disableNameSuffixHash: true